---
title: "FASPCA using a Gabriel Connection Network based weight matrix"
output: html_document
---

*Set Working Directory*
```{r}
setwd("C:/Users/Khoo Tzung Hsuen/Desktop/Research")
```

*Import libraries*
```{r, message=FALSE, warning=FALSE}
library(fda)
library(spdep)
library(ade4)
library(adegenet)
library(adespatial)
library(rgdal)
library(maps)
library(ggplot2)
library(magrittr)
library(stats)
library(sf)
```

*Import Data*
```{r}
stocks_2014_2015 <- read.csv("Stock_Indices_2014-2015.csv", header=T,check.names = F)
stocks_2015_2016 <- read.csv("Stock_Indices_2015-2016.csv", header=T,check.names = F)
stocks_2016_2017 <- read.csv("Stock_Indices_2016-2017.csv", header=T,check.names = F)
stocks_2014_2015 <- stocks_2014_2015[-c(1)]
stocks_2015_2016 <- stocks_2015_2016[-c(1)]
stocks_2016_2017 <- stocks_2016_2017[-c(1)]
stock_rates_2014_2015 <-apply(stocks_2014_2015,2,function(x) diff(log(x), lag=1))
stock_rates_2015_2016 <-apply(stocks_2015_2016,2,function(x) diff(log(x), lag=1))
stock_rates_2016_2017 <-apply(stocks_2016_2017,2,function(x) diff(log(x), lag=1))
```

*Set Locations using World Shape File*
```{r fig.align="center", echo = FALSE,fig.width = 15}
#shape file of countries 
World <-readOGR(dsn="C:/Users/Khoo Tzung Hsuen/Desktop/Research/SGARCH/Codes for SGARCH/World_Cities","World_Cities")
World_Background <- readOGR( 
  dsn= "C:/Users/Khoo Tzung Hsuen/Desktop/Research/SGARCH/Codes for SGARCH/worldborders", 
  layer="TM_WORLD_BORDERS-0.3",
  verbose=FALSE
)

a1<-  which(World@data[, "CITY_NAME"] == "Brasilia") 
a2<-  which(World@data[, "CITY_NAME"] == "Mexico City") 
a3<-  which(World@data[, "CITY_NAME"] == "Buenos Aires")
a4<-  which(World@data[, "CITY_NAME"] == "Amsterdam")
a5<-  which(World@data[, "CITY_NAME"] == "Athens")
a6<-  which(World@data[, "CITY_NAME"] == "Brussels")
a7<-  which(World@data[, "CITY_NAME"] == "Bucharest")
a8<-  which(World@data[, "CITY_NAME"] == "Budapest")
a9<-  which(World@data[, "CITY_NAME"] == "Paris")
a10<- which(World@data[, "CITY_NAME"] == "Berlin")
a11<- which(World@data[, "CITY_NAME"] == "Rome")
a12<- which(World@data[, "CITY_NAME"] == "Helsinki")
a13<- which(World@data[, "CITY_NAME"] == "Madrid")
a14<- which(World@data[, "CITY_NAME"] == "Reykjavik")
a15<- which(World@data[, "CITY_NAME"] == "Riga")
a16<- which(World@data[, "CITY_NAME"] == "Stockholm")
a17<- which(World@data[, "CITY_NAME"] == "Tallinn")   
a18<- which(World@data[, "CITY_NAME"] == "Vilnius")
a19<- which(World@data[, "CITY_NAME"] == "Oslo")
a20<- which(World@data[, "CITY_NAME"] == "Lisbon")
a21<- which(World@data[, "CITY_NAME"] == "Prague")
a22<- which(World@data[, "CITY_NAME"] == "Bratislava")
a23<- which(World@data[, "CITY_NAME"] == "Bern")
a24<- which(World@data[, "CITY_NAME"] == "Sofia")
a25<- which(World@data[, "CITY_NAME"] == "London")
a26<- which(World@data[, "CITY_NAME"] == "Kyiv")
a27<- which(World@data[, "CITY_NAME"] == "Ankara")
a28<- which(World@data[, "CITY_NAME"] == "Canberra")
a29<- which(World@data[, "CITY_NAME"] == "Hong Kong")
a30<- which(World@data[, "CITY_NAME"] == "Jakarta")
a31<- which(World@data[, "CITY_NAME"] == "Kuala Lumpur")
a32<- which(World@data[, "CITY_NAME"] == "Seoul")
a33<- which(World@data[, "CITY_NAME"] == "Tokyo")
a34<- which(World@data[, "CITY_NAME"] == "Wellington")
a35<- which(World@data[, "CITY_NAME"] == "Manila")
a36<- which(World@data[, "CITY_NAME"] == "Bangkok")
a37<- which(World@data[, "CITY_NAME"] == "Beijing")
a38<- which(World@data[, "CITY_NAME"] == "New Delhi")
a39<- which(World@data[, "CITY_NAME"] == "Singapore")
a40<- which(World@data[, "CITY_NAME"] == "Taipei")
a41<- which(World@data[, "CITY_NAME"] == "Vienna")
a42<- which(World@data[, "CITY_NAME"] == "Moscow")
a43<- which(World@data[, "CITY_NAME"] == "Guangzhou")
a44<- which(World@data[, "CITY_NAME"] == "Hanoi")
a45<- which(World@data[, "CITY_NAME"] == "Islamabad")
a46<- which(World@data[, "CITY_NAME"] == "Colombo")
a47<- which(World@data[, "CITY_NAME"] == "Bogota")
a48<- which(World@data[, "CITY_NAME"] == "Lima")
a50<- which(World@data[, "CITY_NAME"] == "Santiago")[1]
a51<- which(World@data[, "CITY_NAME"] == "Sarajevo")
a52<- which(World@data[, "CITY_NAME"] == "Dublin")
a53<- which(World@data[, "CITY_NAME"] == "Warsaw")
a54<- which(World@data[, "CITY_NAME"] == "Copenhagen")
a55<- which(World@data[, "CITY_NAME"] == "Zagreb")
a56<- which(World@data[, "CITY_NAME"] == "Belgrade")
a57<- which(World@data[, "CITY_NAME"] == "Cape Town")
a58<- which(World@data[, "CITY_NAME"] == "Windhoek")
a59<- which(World@data[, "CITY_NAME"] == "Rabat")
a60<- which(World@data[, "CITY_NAME"] == "Tunis")
a61<- which(World@data[, "CITY_NAME"] == "Lusaka")
a62<- which(World@data[, "CITY_NAME"] == "Ottawa")
a63<- which(World@data[, "CITY_NAME"] == "New York")
a64<- which(World@data[, "CITY_NAME"] == "Chicago") 
a65<- which(World@data[, "CITY_NAME"] == "Amman")
a66<- which(World@data[, "CITY_NAME"] == "Riyadh")
a67<- which(World@data[, "CITY_NAME"] == "Doha")
a68<- which(World@data[, "CITY_NAME"] == "Abu Dhabi")
a69<- which(World@data[, "CITY_NAME"] == "Jerusalem")
a70<- which(World@data[, "CITY_NAME"] == "Manama")
a71<- which(World@data[, "CITY_NAME"] == "Muscat")
a72<- which(World@data[, "CITY_NAME"] == "Cairo")

vec_a <- c(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,
           a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,
           a31,a32,a33,a34,a35,a36,a37,a38,a39,a40,a41,a42,a43,a44,
           a45,a46,a47,a48,a50,a51,a52,a53,a54,a55,a56,a57,a58,a59,
           a60,a61,a62,a63,a64,a65,a66,a67,a68,a69,a70,a71,a72)

countries <- World[vec_a,]
countries_df <-data.frame(countries)
countries_df
countries$CITY_NAME
coords_countries <- coordinates(countries)
spdf_fortified <- tidy(World_Background, region = "NAME")
ggplot() +
  geom_polygon(data = spdf_fortified, aes( x = long, y = lat, group = group), fill="yellow", color="grey") +
     theme_void() +
           geom_point(data = countries_df,aes( x = coords.x1, y = coords.x2),pch=16, col="red",cex=3) +
            ylim(-60,80)

spdf_fortified
```

*Create Spatial Weight Matrices*
```{r fig.align="center", echo = FALSE,fig.width = 20}
gnm <-gabrielneigh(coords_countries, nnmult=3)
gnm <-graph2nb(gnm, sym=TRUE) 
gnm_listw <-nb2listw(gnm) 
gnm_sf <- as(nb2lines(nb=gnm, coords=coords_countries), 'sf')
gnm_sf <- st_set_crs(gnm_sf, st_crs(CRS("+proj=longlat +datum=WGS84")))
k <- data.frame(gnm_sf)
gnm
ggplot() +
  geom_polygon(data = spdf_fortified, aes( x = long, y = lat, group = group), fill="yellow", color="grey") +
  geom_sf(data = gnm_sf)+
  geom_point(data = countries_df,aes( x = coords.x1, y = coords.x2),pch=16, col="red",cex=3)+ ylim(-60,90)
```

*Transforming the Log Return Stock Data into Functional Data*
```{r}
lambda1 = 1.2*1e2
t = seq(1,dim(stock_rates_2014_2015)[1])
norder = 4
nbasis1 = length(t) + norder - 2 # Penalty Smoothing
funcbasis = create.bspline.basis(c(1,dim(stock_rates_2014_2015)[1]), nbasis1, norder, t)
accelLfd = int2Lfd(2)
fdParobj1 = fdPar(funcbasis,accelLfd,lambda1) # lambda assumed to be 1 without going through gcv
funcfd.fit = smooth.basis(t, stock_rates_2014_2015, fdParobj1)
Xfd1 = funcfd.fit$fd
coefmat = NULL
coefmat = cbind(coefmat,coef(funcfd.fit))
Xfd1 = fd(coefmat,funcbasis)
data_multi_2014_2015=t(Xfd1$coefs) 
row.names(data_multi_2014_2015) <- countries$NAME

t = seq(1,dim(stock_rates_2015_2016)[1])
norder = 4
nbasis1 = length(t) + norder - 2 # Penalty Smoothing
funcbasis = create.bspline.basis(c(1,dim(stock_rates_2015_2016)[1]), nbasis1, norder, t)
accelLfd = int2Lfd(2)
fdParobj1 = fdPar(funcbasis,accelLfd,lambda1) # lambda assumed to be 1 without going through gcv
funcfd.fit = smooth.basis(t, stock_rates_2015_2016, fdParobj1)
Xfd2 = funcfd.fit$fd
coefmat = NULL
coefmat = cbind(coefmat,coef(funcfd.fit))
Xfd2 = fd(coefmat,funcbasis)
data_multi_2015_2016=t(Xfd2$coefs) 
row.names(data_multi_2015_2016)<- countries$NAME

t = seq(1,dim(stock_rates_2016_2017)[1])
norder = 4
nbasis1 = length(t) + norder - 2 # Penalty Smoothing
funcbasis = create.bspline.basis(c(1,dim(stock_rates_2016_2017)[1]),  nbasis1, norder, t)
accelLfd = int2Lfd(2)
fdParobj1 = fdPar(funcbasis,accelLfd,lambda1) # lambda assumed to be 1 without going through gcv
funcfd.fit = smooth.basis(t, stock_rates_2016_2017, fdParobj1)
Xfd3= funcfd.fit$fd
coefmat = NULL
coefmat = cbind(coefmat,coef(funcfd.fit))
Xfd3 = fd(coefmat,funcbasis)
data_multi_2016_2017=t(Xfd3$coefs) 
row.names(data_multi_2016_2017)<- countries$NAME
```

*FASPCA (2014-2015) (GABRIEL)*
```{r fig.align="center", echo = FALSE,fig.width = 15}
spca22v_gb <- spca(data_multi_2014_2015,xy=coords_countries, cn=gnm_listw,ask=FALSE,scannf=TRUE,nfposi =2,nfnega =2)
par(mar=c(5,6,4,1)+.1)
ylab = expression(paste("Numerical value of eigenvalues ( " ~ 10^-5, ")"))
barplot(spca22v_gb$eig*10^5, main="Eigenvalues of sPCA", col = heat.colors(length(spca22v_gb$eig)),
          ylab=ylab,cex.axis=1.3,cex.lab=1.3) 

set.seed(1234)
moran.mc(spca22v_gb$li[,1],gnm_listw, 999)
moran.mc(spca22v_gb$li[,2],gnm_listw, 999)
moran.mc(spca22v_gb$li[,3],gnm_listw,alternative = "less", 999) #1st negative
moran.mc(spca22v_gb$li[,4],gnm_listw,alternative = "less", 999) #2nd negative

#the % variability
round(abs(spca22v_gb$eig[1])*100 /sum(abs(spca22v_gb$eig)) ,2)
round(abs(spca22v_gb$eig[2])*100 /sum(abs(spca22v_gb$eig)) ,2)
round(abs(spca22v_gb$eig[70])*100 /sum(abs(spca22v_gb$eig)) ,2)
round(abs(spca22v_gb$eig[69])*100 /sum(abs(spca22v_gb$eig)) ,2)

#the first positive
par(mar=c(0.5,0.5,2.5,0.5))
plot(World_Background,col="#FFFFA8FF", border="black", lwd=0.2, ylim=c(-20,80))
s.value(coords_countries, spca22v_gb$ls[,1], add.p=TRUE, csize=0.5,clegend = 1.2)
plot(World_Background, xlim=c(8,9), ylim=c(30,67),col="#FFFFA8FF", border="black", lwd=0.2)
s.value(coords_countries, spca22v_gb$ls[,1], add.p=TRUE, csize=0.5,clegend = 1.2)


#the second positive
par(mar=c(0.5,0.5,2.5,0.5))
plot(World_Background,col="#FFFFA8FF", border="black", lwd=0.2, ylim=c(-20,80))
s.value(coords_countries, spca22v_gb$ls[,2], add.p=TRUE, csize=0.5,clegend = 1.2)
plot(World_Background, xlim=c(8,9), ylim=c(30,67),col="#FFFFA8FF", border="black", lwd=0.2)
s.value(coords_countries, spca22v_gb$ls[,2], add.p=TRUE, csize=0.5,clegend = 1.2)

```

*FASPCA (2015-2016) (GABRIEL)*
```{r fig.align="center", echo = FALSE,fig.width = 15}
spca22v_gb <- spca(data_multi_2015_2016,xy=coords_countries, cn=gnm_listw,ask=FALSE,scannf=TRUE,nfposi =2,nfnega =2)

par(mar=c(5,6,4,1)+.1)
ylab = expression(paste("Numerical value of eigenvalues ( " ~ 10^-5, ")"))
barplot(spca22v_gb$eig*10^5, main="Eigenvalues of sPCA", col = heat.colors(length(spca22v_gb$eig)),
          ylab=ylab,cex.axis=1.3,cex.lab=1.3) 

set.seed(1234)
moran.mc(spca22v_gb$li[,1],gnm_listw, 999)
moran.mc(spca22v_gb$li[,2],gnm_listw, 999)
moran.mc(spca22v_gb$li[,3],gnm_listw,alternative = "less", 999) #1st negative
moran.mc(spca22v_gb$li[,4],gnm_listw,alternative = "less", 999) #2nd negative

#the % variability
round(abs(spca22v_gb$eig[1])*100 /sum(abs(spca22v_gb$eig)) ,2)
round(abs(spca22v_gb$eig[2])*100 /sum(abs(spca22v_gb$eig)) ,2)
round(abs(spca22v_gb$eig[70])*100 /sum(abs(spca22v_gb$eig)) ,2)
round(abs(spca22v_gb$eig[69])*100 /sum(abs(spca22v_gb$eig)) ,2)

#the first positive
par(mar=c(0.5,0.5,2.5,0.5))
plot(World_Background,col="#FFFFA8FF", border="black", lwd=0.2, ylim=c(-20,80))
s.value(coords_countries, spca22v_gb$ls[,1], add.p=TRUE, csize=0.5,clegend = 1.2)
plot(World_Background, xlim=c(8,9), ylim=c(30,67),col="#FFFFA8FF", border="black", lwd=0.2)
s.value(coords_countries, spca22v_gb$ls[,1], add.p=TRUE, csize=0.5,clegend = 1.2)

#the second positive
par(mar=c(0.5,0.5,2.5,0.5))
plot(World_Background,col="#FFFFA8FF", border="black", lwd=0.2, ylim=c(-20,80))
s.value(coords_countries, spca22v_gb$ls[,2], add.p=TRUE, csize=0.5,clegend = 1.2)
plot(World_Background, xlim=c(8,9), ylim=c(30,67),col="#FFFFA8FF", border="black", lwd=0.2)
s.value(coords_countries, spca22v_gb$ls[,2], add.p=TRUE, csize=0.5,clegend = 1.2)

```

*FASPCA (2016-2017) (GABRIEL)*
```{r fig.align="center", echo = FALSE,fig.width = 15}
spca22v_gb <- spca(data_multi_2016_2017, xy=coords_countries, cn=gnm_listw,ask=FALSE,scannf=TRUE,nfposi =2,nfnega =2)

par(mar=c(5,6,4,1)+.1)
ylab = expression(paste("Numerical value of eigenvalues ( " ~ 10^-5, ")"))
barplot(spca22v_gb$eig*10^5, main="Eigenvalues of sPCA", col = heat.colors(length(spca22v_gb$eig)),
          ylab=ylab,cex.axis=1.3,cex.lab=1.3) 


set.seed(1234)
moran.mc(spca22v_gb$li[,1],gnm_listw, 999)
moran.mc(spca22v_gb$li[,2],gnm_listw, 999)
moran.mc(spca22v_gb$li[,3],gnm_listw,alternative = "less", 999) #1st negative
moran.mc(spca22v_gb$li[,4],gnm_listw,alternative = "less", 999) #2nd negative

#the % variability
round(abs(spca22v_gb$eig[1])*100 /sum(abs(spca22v_gb$eig)) ,2)
round(abs(spca22v_gb$eig[2])*100 /sum(abs(spca22v_gb$eig)) ,2)
round(abs(spca22v_gb$eig[70])*100 /sum(abs(spca22v_gb$eig)) ,2)
round(abs(spca22v_gb$eig[69])*100 /sum(abs(spca22v_gb$eig)) ,2)

#the first positive
par(mar=c(0.5,0.5,2.5,0.5))
plot(World_Background,col="#FFFFA8FF", border="black", lwd=0.2, ylim=c(-20,80))
s.value(coords_countries, spca22v_gb$ls[,1], add.p=TRUE, csize=0.5,clegend = 1.2)
plot(World_Background, xlim=c(8,9), ylim=c(30,67),col="#FFFFA8FF", border="black", lwd=0.2)
s.value(coords_countries, spca22v_gb$ls[,1], add.p=TRUE, csize=0.5,clegend = 1.2)

#the second positive
par(mar=c(0.5,0.5,2.5,0.5))
plot(World_Background,col="#FFFFA8FF", border="black", lwd=0.2, ylim=c(-20,80))
s.value(coords_countries, spca22v_gb$ls[,2], add.p=TRUE, csize=0.5,clegend = 1.2)
plot(World_Background, xlim=c(8,9), ylim=c(30,67),col="#FFFFA8FF", border="black", lwd=0.2)
s.value(coords_countries, spca22v_gb$ls[,2], add.p=TRUE, csize=0.5,clegend = 1.2)

```
